name: Train Fund Vehicle Classifier

on:
  workflow_dispatch:    # manual trigger in the Actions tab
  schedule:
    - cron: '0 2 * * 0'  # weekly retrain every Sunday at 02:00 UTC

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true    # if you used Git LFS for the CSV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib

      - name: Train model
        run: python train_fund_classifier.py

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: fund_vehicle_model
          path: fund_vehicle_clf.joblib
