theme: jekyll-theme-cayman

title: "Fund Tracker Dashboard"
description: "Interactive Companies House dashboard"

baseurl: "/fund-tracker-dashboard"
url: "https://finncampbell.github.io"

future: false

exclude:
  - master_companies.xlsx
  - fund_tracker.log
  - api_logs.json
