theme: jekyll-theme-cayman

title: "Fund Tracker Dashboard"
description: "Interactive Companies House dashboard using Jekyll + DataTables"

baseurl: "/fund-tracker-dashboard"
url: "https://finncampbell.github.io"

future: false
