theme: jekyll-theme-cayman

title: "Fund Tracker Dashboard"
description: "Interactive Companies House dashboard using Jekyll + DataTables"

baseurl: "/fund-tracker-dashboard"        # <- your repo name, with slash
url: "https://finncampbell.github.io"     # <- your GitHub username
future: false
