# netlify.toml — only functions, no static build
[build]
  command   = "echo \"No build for UI—static served by GitHub Pages\""
  publish   = "."              # unused for UI
  functions = "netlify/functions"

[functions]
  node_bundler = "nft"
