# netlify.toml

[build]
  command   = "echo \"Skipping build\""
  publish   = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "nft"

[[headers]]
  for = "/assets/data/*.csv"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
