# .github/workflows/backfill-week.yml
name: Fund Tracker Historical Backfill

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: true
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: true
  schedule:
    - cron: '0 10 * * *'    # optional daily at 10:00 UTC

permissions:
  contents: write
  actions: read

concurrency:
  group: fund-tracker
  cancel-in-progress: true

jobs:
  backfill:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      CH_API_KEY: ${{ secrets.CH_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull latest JSON
        run: git pull origin main

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip, setuptools, wheel
        run: pip install --upgrade pip setuptools wheel

      - name: Pre-install NumPy wheel
        run: pip install --prefer-binary --only-binary=":all:" 'numpy>=1.24.0,<2.0.0'

      - name: Install dependencies
        run: pip install --prefer-binary --only-binary=":all:" -r requirements.txt

      - name: Configure Git
        run: |
          git config user.email "bot@example.com"
          git config user.name  "GH Actions Bot"

      # Stage 1: re-ingest companies over the range
      - name: Run fund_tracker.py for range
        run: |
          python fund_tracker.py \
            --start_date "${{ github.event.inputs.start_date }}" \
            --end_date   "${{ github.event.inputs.end_date }}"

      - name: Commit companies data
        run: |
          git add assets/data/master_companies.* assets/data/relevant_companies.*
          if ! git diff --cached --quiet; then
            git commit -m "Backfill: update companies ${ { github.event.inputs.start_date } }→${{ github.event.inputs.end_date }}"
            git push origin main
          fi

      # Stage 2: backfill directors for that same range
      - name: Run backfill_directors.py
        run: |
          python backfill_directors.py \
            --start_date "${{ github.event.inputs.start_date }}" \
            --end_date   "${{ github.event.inputs.end_date }}"

      - name: Commit directors data
        run: |
          git add assets/data/directors.json
          if ! git diff --cached --quiet; then
            git commit -m "Backfill: update directors ${ { github.event.inputs.start_date } }→${{ github.event.inputs.end_date }}"
            git push origin main
          fi

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: fund-tracker-backfill-logs
          path: assets/logs/fund_tracker.log
