name: Build FRN Profiles

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code (includes fca_cf.zip)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: List FCA data files
        run: |
          echo "Firm slices:"
          ls -1 fca-dashboard/data
          echo "CF archive:"
          ls -lh docs/fca-dashboard/data/fca_cf.zip
          echo "Verify inside ZIP:"
          unzip -l docs/fca-dashboard/data/fca_cf.zip | head -n 20
          echo "Profile stubs:"
          ls -1 docs/fca-dashboard/data/frn | head -10

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Merge FCA data into profiles
        run: python3 fca-dashboard/scripts/build_frn_profiles.py

      - name: Commit & push updated profiles
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add docs/fca-dashboard/data/frn/*.json
          git diff --cached --quiet || git commit -m "chore(fca): rebuild FRN profiles"
          git push origin HEAD:main
