name: Build FRN Profiles

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Download CF chunk artifacts
        uses: actions/download-artifact@v4
        with:
          path: chunks

      - name: Merge FCA data into profiles
        run: |
          python3 fca-dashboard/scripts/build_frn_profiles.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add docs/fca-dashboard/data/frn/*.json
          git diff --cached --quiet || git commit -m "chore(fca): merge profile data"
          git push origin HEAD:main
