name: Combine All Code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel
          pip install --only-binary=:all: -r requirements.txt

      - name: Run combine script
        run: |
          chmod +x scripts/combine_code.py
          ./scripts/combine_code.py -o combined_code.txt

      - name: Upload combined file
        uses: actions/upload-artifact@v4
        with:
          name: all-code
          path: combined_code.txt
