name: Fetch FCA Firm Individuals (Ad-hoc)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      chunks:
        description: 'Number of parallel chunks to split the FRN list into'
        required: true
        default: '4'
      limit:
        description: 'Max FRNs per chunk (blank = full list)'
        required: false
        default: ''

jobs:
  split:
    runs-on: ubuntu-latest
    outputs:
      chunk_list: ${{ steps.set-chunks.outputs.chunk_list }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: set-chunks
        name: Compute chunk start indices
        run: |
          # count total FRNs
          TOTAL=$(jq 'length' fca-dashboard/data/all_frns_with_names.json)
          # number of parallel chunks, from dispatch input
          CHUNKS=${{ github.event.inputs.chunks }}

          # split into N equal-sized windows
          python3 - << 'EOF' > indices.json
import math, json
total = int("$TOTAL")
n     = int("$CHUNKS")
size  = math.ceil(total / n)
indices = list(range(0, total, size))
print(json.dumps(indices))
EOF

          # expose to subsequent jobs
          echo "chunk_list=$(cat indices.json)" >> $GITHUB_OUTPUT

  fetch:
    needs: split
    runs-on: ubuntu-latest
    strategy:
      matrix:
        start: ${{ fromJson(needs.split.outputs.chunk_list) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Determine limit parameter
        id: calc-limit
        run: |
          if [ -n "${{ github.event.inputs.limit }}" ]; then
            echo "limit=--limit ${{ github.event.inputs.limit }}" >> $GITHUB_OUTPUT
          else
            echo "limit=" >> $GITHUB_OUTPUT
          fi

      - name: Fetch individuals chunk
        run: |
          OFFSET=${{ matrix.start }}
          python3 fca-dashboard/scripts/fetch_firm_individuals.py --offset $OFFSET ${{ steps.calc-limit.outputs.limit }}

      - name: Upload chunk artifact
        uses: actions/upload-artifact@v4
        with:
          name: individuals-chunk-${{ matrix.start }}
          path: fca-dashboard/data/fca_individuals_by_firm.json

  merge:
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download all chunk artifacts
        uses: actions/download-artifact@v4
        with:
          path: chunks

      - name: Merge chunk files
        run: |
          python3 fca-dashboard/scripts/merge_fca_individuals.py chunks fca-dashboard/data/fca_individuals_by_firm.json

      - name: Commit & push merged data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add fca-dashboard/data/fca_individuals_by_firm.json
          git diff --cached --quiet || git commit -m "chore(fca): merge firm individuals chunks"
          git push origin HEAD:main
