# .github/workflows/fetch-main.yml
name: Fetch FCA Main Records (Ad‑hoc)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'How many FRNs to fetch (blank = full run)'
        required: false
        default: ''

jobs:
  fetch-main:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Pull latest main
        run: git pull --rebase origin main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch main firm records
        env:
          FCA_API_EMAIL: ${{ secrets.FCA_API_EMAIL }}
          FCA_API_KEY:   ${{ secrets.FCA_API_KEY }}
        run: |
          if [ -n "${{ github.event.inputs.limit }}" ]; then
            python fca-dashboard/scripts/fetch_main.py --limit ${{ github.event.inputs.limit }}
          else
            python fca-dashboard/scripts/fetch_main.py
          fi

      - name: Commit & push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add fca-dashboard/data/fca_main.json
          git diff --cached --quiet || git commit -m "chore(fca): update main records"
          git push origin HEAD:main
