name: Fetch FCA Main Slice

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  split:
    runs-on: ubuntu-latest
    outputs:
      shards: ${{ steps.set.outputs.shards }}
      indices: ${{ steps.set.outputs.indices }}
    steps:
      - uses: actions/checkout@v3
      - id: set
        run: |
          python3 - <<'EOF'
          import json, math
          frns = json.load(open('docs/fca-dashboard/data/all_frns_with_names.json'))
          total, shards = len(frns), 5
          size = math.ceil(total/shards)
          offsets = [i*size for i in range(shards)]
          print(f"::set-output name=shards::{shards}")
          print("::set-output name=indices::" + ",".join(map(str, offsets)))
          EOF

  fetch:
    needs: split
    strategy:
      matrix:
        shard-index: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest
    env:
      FCA_API_KEY:   ${{ secrets.FCA_API_KEY }}
      FCA_API_EMAIL: ${{ secrets.FCA_API_EMAIL }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python & deps
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests

      - name: Fetch shard #${{ matrix.shard-index }}
        run: |
          python3 fca-dashboard/scripts/fetch_main.py \
            --shards ${{ needs.split.outputs.shards }} \
            --shard-index ${{ matrix.shard-index }} \
            --threads 5 \
            --only-missing

      - name: Upload main shard
        uses: actions/upload-artifact@v4
        with:
          name: main-shard-${{ matrix.shard-index }}
          path: fca-dashboard/data/fca_main_shard_${{ matrix.shard-index }}.json

  merge:
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Download all shards
        uses: actions/download-artifact@v4
        with:
          path: fca-dashboard/data

      - name: Merge main shards
        run: |
          python3 - <<'EOF'
          import json, glob
          combined = {}
          for shard in glob.glob('fca-dashboard/data/fca_main_shard_*.json'):
              combined.update(json.load(open(shard, encoding="utf-8")))
          with open('fca-dashboard/data/fca_main.json','w', encoding="utf-8") as f:
              json.dump(combined, f, indent=2, ensure_ascii=False)
          print(f"Merged {len(combined)} FRNs")
          EOF

      - name: Commit & push merged main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add fca-dashboard/data/fca_main.json
          git diff --cached --quiet || git commit -m "chore(fca): merge main shards"
          git push origin HEAD:main
