name: Fetch FCA Appointed Representatives (Ad‑hoc)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'How many FRNs to fetch ARs for (blank = full run)'
        required: false
        default: ''

jobs:
  fetch-ars:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Pull latest main
        run: git pull --rebase origin main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch appointed representatives
        env:
          FCA_API_EMAIL: ${{ secrets.FCA_API_EMAIL }}
          FCA_API_KEY:   ${{ secrets.FCA_API_KEY }}
        run: |
          if [ -n "${{ github.event.inputs.limit }}" ]; then
            python fca-dashboard/scripts/fetch_ars.py --limit ${{ github.event.inputs.limit }}
          else
            python fca-dashboard/scripts/fetch_ars.py
          fi

      - name: Commit & push updated AR data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add fca-dashboard/data/fca_ars.json
          git diff --cached --quiet || git commit -m "chore(fca): update appointed reps"
          git push origin HEAD:main
