name: Fetch FCA Trading Names (Ad‑hoc)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'How many FRNs to fetch names for (blank = full run)'
        required: false
        default: ''

jobs:
  fetch-names:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch trading/other names
        env:
          FCA_API_EMAIL: ${{ secrets.FCA_API_EMAIL }}
          FCA_API_KEY:   ${{ secrets.FCA_API_KEY }}
        run: |
          if [ -n "${{ github.event.inputs.limit }}" ]; then
            python fca-dashboard/scripts/fetch_names.py --limit ${{ github.event.inputs.limit }}
          else
            python fca-dashboard/scripts/fetch_names.py
          fi

      - name: Commit & push updated names
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git pull --rebase origin main
          git add fca-dashboard/data/fca_names.json
          git diff --cached --quiet || git commit -m "chore(fca): update trading names"
          git push origin HEAD:main
