# ============================================================================= 
# Workflow: Fetch FCA Firm Individuals (Ad-hoc)
# =============================================================================
name: Fetch FCA Firm Individuals (Ad-hoc)

permissions:
  contents: write  # so the merge job can push back

on:
  workflow_dispatch:
    inputs:
      chunks:
        description: 'Number of parallel chunks (default 5)'
        required: true
        default: '5'
      limit:
        description: 'Max FRNs per chunk (blank = full slice)'
        required: false
        default: ''

jobs:
  # ---------------------------------------------------------------------------
  # JOB 1: split
  #   - Partition the FRN list into N start offsets
  #   - Emit both `chunk_list` and `chunk_count`
  # ---------------------------------------------------------------------------
  split:
    runs-on: ubuntu-latest
    outputs:
      chunk_list: ${{ steps.set-chunks.outputs.chunk_list }}
      chunk_count: ${{ steps.set-chunks.outputs.chunk_count }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - id: set-chunks
        name: Compute chunk start indices
        run: |
          # 1. Count total FRNs
          TOTAL=$(jq 'length' fca-dashboard/data/all_frns_with_names.json)

          # 2. Desired parallel chunks
          CHUNKS=${{ github.event.inputs.chunks }}

          # 3. Compute evenly spaced offsets
          python3 -c "import math, json; total=int('$TOTAL'); n=int('$CHUNKS'); size=math.ceil(total/n); print(json.dumps(list(range(0,total,size))))" \
            > indices.json

          # 4. Expose list for fetch matrix
          echo "chunk_list=$(cat indices.json)" >> $GITHUB_OUTPUT

          # 5. Expose count for rate limit calc
          echo "chunk_count=$(jq 'length' indices.json)" >> $GITHUB_OUTPUT

  # ---------------------------------------------------------------------------
  # JOB 2: fetch
  #   - Parallel workers: each fetches one slice of FRNs
  #   - Throttles API calls to floor(50/COUNT) per 10s
  # ---------------------------------------------------------------------------
  fetch:
    needs: split
    runs-on: ubuntu-latest
    strategy:
      matrix:
        start: ${{ fromJson(needs.split.outputs.chunk_list) }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Fetch individuals chunk (throttled)
        env:
          FCA_API_EMAIL: ${{ secrets.FCA_API_EMAIL }}
          FCA_API_KEY:   ${{ secrets.FCA_API_KEY }}
        run: |
          # 1. Offset & total chunks
          OFFSET=${{ matrix.start }}
          COUNT=${{ needs.split.outputs.chunk_count }}

          # 2. Compute per-worker rate limit
          RL_MAX_CALLS=$((50 / COUNT))
          RL_WINDOW_S=10
          echo "🔢 Rate limit: $RL_MAX_CALLS calls per $RL_WINDOW_S seconds"

          # 3. Export for RateLimiter
          export RL_MAX_CALLS RL_WINDOW_S

          # 4. Pass --limit for testing, if provided
          if [ -n "${{ github.event.inputs.limit }}" ]; then
            LIMIT="--limit ${{ github.event.inputs.limit }}"
          else
            LIMIT=""
          fi

          # 5. Prepare output dir
          OUT_DIR="chunks/individuals-chunk-${OFFSET}"
          mkdir -p "$OUT_DIR"

          # 6. Invoke the chunked fetch script
          python3 fca-dashboard/scripts/fetch_firm_individuals.py \
            --offset "$OFFSET" $LIMIT \
            --output "$OUT_DIR/fca_individuals_by_firm.json"

      - name: Upload chunk artifact
        uses: actions/upload-artifact@v4
        with:
          name: individuals-chunk-${{ matrix.start }}
          path: chunks/individuals-chunk-${{ matrix.start }}/fca_individuals_by_firm.json

  # ---------------------------------------------------------------------------
  # JOB 3: merge
  #   - Download all artifacts, merge into single UI JSON, commit if changed
  # ---------------------------------------------------------------------------
  merge:
    needs: fetch
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download chunk artifacts
        uses: actions/download-artifact@v4
        with:
          path: chunks

      - name: Merge into UI data folder
        run: |
          mkdir -p docs/fca-dashboard/data
          python3 fca-dashboard/scripts/merge_fca_individuals.py \
            chunks docs/fca-dashboard/data/fca_individuals_by_firm.json

      - name: Commit & push merged result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"

          git add docs/fca-dashboard/data/fca_individuals_by_firm.json
          git diff --cached --quiet || git commit -m "chore(fca): merge firm individuals into docs"
          git push origin HEAD:main
