# .github/workflows/fetch-directors.yml
name: Fetch Directors

permissions:
  contents: write
  actions: read

on:
  workflow_dispatch:

jobs:
  fetch-directors:
    runs-on: ubuntu-latest
    env:
      CH_API_KEY:   ${{ secrets.CH_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # 1) Checkout main so we have requirements.txt & scripts
      - name: Check out code (main)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2) Clone data branch separately
      - name: Clone data branch
        run: |
          git clone --branch data \
            https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} \
            data-branch

      # 3) Seed existing CSV/JSON into docs/assets/data/
      - name: Bootstrap existing data files
        run: |
          mkdir -p docs/assets/data
          cp data-branch/docs/assets/data/relevant_companies.csv docs/assets/data/
          cp data-branch/docs/assets/data/directors.json          docs/assets/data/  || true
          cp data-branch/docs/assets/data/no_directors.json       docs/assets/data/  || true

      # 4) Restore rate limiter cache
      - name: Restore rate_limiter.db cache
        uses: actions/cache@v3
        with:
          path: rate_limiter.db
          key: rate-limiter-db

      # 5) Set up Python & install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt

      # 6) Run the fetch_directors script
      - name: Fetch directors for relevant companies
        run: python fetch_directors.py

      # 7) Save rate limiter state
      - name: Save rate_limiter.db to cache
        uses: actions/cache@v3
        with:
          path: rate_limiter.db
          key: rate-limiter-db

      # 8) Copy updated JSONs back into the data-branch clone
      - name: Copy updated JSONs into data-branch
        run: |
          cp docs/assets/data/directors.json    data-branch/docs/assets/data/
          cp docs/assets/data/no_directors.json data-branch/docs/assets/data/

      # 9) Commit & push on data branch
      - name: Commit & push updated directors
        run: |
          cd data-branch
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/assets/data/directors.json docs/assets/data/no_directors.json
          if git diff --cached --quiet; then
            echo "No changes to directors/no_directors — skipping push"
            exit 0
          fi
          git commit -m "chore(data): update directors.json [skip ci]"
          git push origin data
