name: Fetch FCA Firm Individuals (Ad-hoc)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      chunks:
        description: 'Number of parallel chunks to split the FRN list into'
        required: false
        default: '4'
      limit:
        description: 'Max FRNs per chunk (blank = full list)'
        required: false
        default: ''

jobs:
  split:
    runs-on: ubuntu-latest
    outputs:
      chunk-list: ${{ steps.build.outputs.chunk_list }}
      total_frns: ${{ steps.build.outputs.total_frns }}

    steps:
      - uses: actions/checkout@v3

      - name: Build chunk list
        id: build
        run: |
          total=$(jq 'length' fca-dashboard/data/all_frns_with_names.json)
          N=${{ github.event.inputs.chunks }}
          # produce JSON array [0,1,2,...,N-1]
          chunk_list=$(jq -n --arg n "$N" '[range(0; ($n|tonumber))]')
          echo "chunk_list=$chunk_list" >> "$GITHUB_OUTPUT"
          echo "total_frns=$total"      >> "$GITHUB_OUTPUT"

  fetch:
    needs: split
    strategy:
      matrix:
        chunk: ${{ fromJson(needs.split.outputs.chunk-list) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Calculate this chunk’s window
        id: slice
        run: |
          N=${{ github.event.inputs.chunks }}
          total=${{ needs.split.outputs.total_frns }}
          chunk_index=${{ matrix.chunk }}

          # evenly divide total into N, rounding up
          per=$(( (total + N - 1) / N ))
          offset=$(( chunk_index * per ))

          echo "offset=$offset" >> $GITHUB_OUTPUT
          echo "limit=$per"     >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch individuals chunk #${{ matrix.chunk }}
        env:
          FCA_API_EMAIL: ${{ secrets.FCA_API_EMAIL }}
          FCA_API_KEY:   ${{ secrets.FCA_API_KEY }}
        run: |
          python fca-dashboard/scripts/fetch_firm_individuals.py \
            --offset ${{ steps.slice.outputs.offset }} \
            --limit  ${{ steps.slice.outputs.limit }}

      - name: Upload this chunk’s result
        uses: actions/upload-artifact@v3
        with:
          name: chunk-${{ matrix.chunk }}
          path: fca-dashboard/data/fca_individuals_by_firm.json

  merge:
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download all chunk artifacts
        uses: actions/download-artifact@v3
        with:
          path: fca-dashboard/data/chunks

      - name: Merge partial JSONs
        run: |
          python fca-dashboard/scripts/merge_fca_individuals.py \
            --input-dir fca-dashboard/data/chunks \
            --output   fca-dashboard/data/fca_individuals_by_firm.json

      - name: Commit & push merged file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add fca-dashboard/data/fca_individuals_by_firm.json
          git diff --cached --quiet || git commit -m "chore(fca): merge firm individuals"
          git push origin HEAD:main
