name: Fetch FCA Firm Individuals (Ad-hoc)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      chunks:
        description: 'Number of parallel chunks to split the FRN list into'
        required: true
        default: '4'
      limit:
        description: 'Max FRNs per chunk (blank = full list)'
        required: false
        default: ''

jobs:
  split:
    runs-on: ubuntu-latest
    outputs:
      chunk_list: ${{ steps.set-chunks.outputs.chunk_list }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - id: set-chunks
        name: Compute chunk start indices
        run: |
          TOTAL=$(jq 'length' fca-dashboard/data/all_frns_with_names.json)
          CHUNKS=${{ github.event.inputs.chunks }}
          python - <<EOF > indices.json
import math, json
total = int($TOTAL)
n = int("$CHUNKS")
size = math.ceil(total / n)
print(json.dumps(list(range(0, total, size))))
EOF
          echo "chunk_list=$(cat indices.json)" >> $GITHUB_OUTPUT

  fetch:
    needs: split
    runs-on: ubuntu-latest
    strategy:
      matrix:
        start: ${{ fromJson(needs.split.outputs.chunk_list) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch individuals (offset ${{ matrix.start }})
        env:
          FCA_API_EMAIL: ${{ secrets.FCA_API_EMAIL }}
          FCA_API_KEY:   ${{ secrets.FCA_API_KEY }}
        run: |
          OFFSET=${{ matrix.start }}
          mkdir -p fca-dashboard/data
          if [ -n "${{ github.event.inputs.limit }}" ]; then
            python fca-dashboard/scripts/fetch_firm_individuals.py \
              --offset $OFFSET \
              --limit ${{ github.event.inputs.limit }} \
              --output fca-dashboard/data/individuals_chunk_${OFFSET}.json
          else
            python fca-dashboard/scripts/fetch_firm_individuals.py \
              --offset $OFFSET \
              --output fca-dashboard/data/individuals_chunk_${OFFSET}.json
          fi

      - name: Upload this chunk
        uses: actions/upload-artifact@v4
        with:
          name: individuals-chunk-${{ matrix.start }}
          path: fca-dashboard/data/individuals_chunk_${{ matrix.start }}.json

  merge:
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download chunk artifacts
        uses: actions/download-artifact@v4
        with:
          path: chunks

      - name: Merge all chunks
        run: |
          python fca-dashboard/scripts/merge_fca_individuals.py \
            chunks \
            fca-dashboard/data/fca_individuals_by_firm.json

      - name: Commit & push merged JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add fca-dashboard/data/fca_individuals_by_firm.json
          git diff --cached --quiet || git commit -m "chore(fca): merge firm individuals"
          git push origin HEAD:main
