name: Fetch FCA Firm Individuals (Ad-hoc)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'Max FRNs per chunk (blank = full list)'
        required: false
        default: ''
      chunks:
        description: 'Number of parallel chunks'
        required: false
        default: '4'

jobs:
  split:
    runs-on: ubuntu-latest
    outputs:
      chunk-list: ${{ steps.calc.outputs.chunk-list }}
    steps:
      - uses: actions/checkout@v3

      - name: Calculate chunk offsets
        id: calc
        run: |
          FILE=docs/fca-dashboard/data/all_frns_with_names.json
          full=$(jq 'length' "$FILE")
          total=${{ github.event.inputs.limit }} 
          total=${{ total:-$full }}
          chunks=${{ github.event.inputs.chunks }}
          step=$(( (total + chunks - 1) / chunks ))
          offsets=()
          for ((i=0; i<total; i+=step)); do offsets+=($i); done
          json="[$(printf '%s,' "${offsets[@]}" | sed 's/,$//')]"
          echo "chunk-list=$json" >> $GITHUB_OUTPUT

  fetch:
    needs: split
    runs-on: ubuntu-latest
    strategy:
      matrix:
        offset: ${{ fromJson(needs.split.outputs.chunk-list) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: python-version: '3.x'
      - run: pip install requests
      - name: Fetch chunk ${{ matrix.offset }}
        env:
          FCA_API_EMAIL: ${{ secrets.FCA_API_EMAIL }}
          FCA_API_KEY:   ${{ secrets.FCA_API_KEY }}
        run: |
          mkdir -p fca-dashboard/data
          python fca-dashboard/scripts/fetch_firm_individuals.py \
            --offset ${{ matrix.offset }} \
            --limit ${{ github.event.inputs.limit }} \
            --output fca-dashboard/data/individuals_chunk_${{ matrix.offset }}.json
      - uses: actions/upload-artifact@v4
        with:
          name: individuals-chunk-${{ matrix.offset }}
          path: fca-dashboard/data/individuals_chunk_${{ matrix.offset }}.json

  merge:
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with: path: chunks/
      - name: Merge chunks
        run: |
          python fca-dashboard/scripts/merge_fca_individuals.py \
            chunks/ fca-dashboard/data/fca_individuals_by_firm.json
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add fca-dashboard/data/fca_individuals_by_firm.json
          git diff --cached --quiet || git commit -m "chore(fca): update firm individuals"
          git push origin HEAD:main
