name: Fetch FCA Individual Records (Sharded)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      threads:
        description: 'Number of threads per shard (optimum ≃5)'
        required: true
        default: '5'
      shards:
        description: 'Number of sequential shards to split IRN list into'
        required: true
        default: '1'
      limit:
        description: 'Max IRNs to process (blank = full run)'
        required: false
        default: ''
      only_missing:
        description: 'Only fetch IRNs not yet present in store'
        required: false
        default: false
        type: boolean
      retry_failed:
        description: 'Only retry IRNs that errored last run'
        required: false
        default: false
        type: boolean
      fresh:
        description: 'Full refresh: ignore existing data'
        required: false
        default: false
        type: boolean
      dry_run:
        description: 'Dry run: list IRNs without making any API calls'
        required: false
        default: false
        type: boolean
      no_push:
        description: 'Don’t commit/push the JSON outputs (for testing)'
        required: false
        default: false
        type: boolean

jobs:
  fetch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: ${{ fromJson(format('[{}]', join(',', range(1, int(github.event.inputs.shards)+1)))) }}
      max-parallel: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch shard ${{ matrix.shard }}
        env:
          FCA_API_EMAIL: ${{ secrets.FCA_API_EMAIL }}
          FCA_API_KEY:   ${{ secrets.FCA_API_KEY }}
        run: |
          python3 fca-dashboard/scripts/fetch_persons.py \
            --threads ${{ github.event.inputs.threads }} \
            --shards ${{ github.event.inputs.shards }} \
            --shard-index ${{ matrix.shard }} \
            $([[ -n "${{ github.event.inputs.limit }}" ]] && echo "--limit ${{ github.event.inputs.limit }}") \
            $([[ "${{ github.event.inputs.only_missing }}" == "true" ]] && echo "--only-missing") \
            $([[ "${{ github.event.inputs.retry_failed }}" == "true" ]] && echo "--retry-failed") \
            $([[ "${{ github.event.inputs.fresh }}" == "true" ]] && echo "--fresh") \
            $([[ "${{ github.event.inputs.dry_run }}" == "true" ]] && echo "--dry-run")

      - name: Upload shard artifact
        uses: actions/upload-artifact@v4
        with:
          name: persons-part-${{ matrix.shard }}
          path: docs/fca-dashboard/data/fca_persons_part${{ matrix.shard }}.json

  merge:
    needs: fetch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Download all shard artifacts
        uses: actions/download-artifact@v4
        with:
          path: docs/fca-dashboard/data

      - name: Merge partitioned JSONs
        run: python3 fca-dashboard/scripts/merge_person_parts.py \
          docs/fca-dashboard/data docs/fca-dashboard/data/fca_persons.json

      - name: Commit & push merged JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add docs/fca-dashboard/data/fca_persons.json
          git diff --cached --quiet || git commit -m "chore(fca): merge individual records"
          git pull --rebase origin main
          git push origin HEAD:main
