name: Fetch FCA Firm Individuals (Ad-hoc)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      chunks:
        description: 'JSON array of zero-based chunk indices (e.g. [0,1,2,3])'
        required: true
        default: '[0,1,2,3]'
      limit:
        description: 'Number of FRNs per chunk (blank = full list segment)'
        required: false
        default: ''

jobs:
  fetch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk: ${{ fromJson(github.event.inputs.chunks) }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch individuals chunk ${{ matrix.chunk }}
        env:
          FCA_API_EMAIL: ${{ secrets.FCA_API_EMAIL }}
          FCA_API_KEY:   ${{ secrets.FCA_API_KEY }}
        run: |
          CMD="python fca-dashboard/scripts/fetch_firm_individuals.py --offset ${{ matrix.chunk }}"
          if [ -n "${{ github.event.inputs.limit }}" ]; then
            CMD+=" --limit ${{ github.event.inputs.limit }}"
          fi
          echo "▶️ Running: $CMD"
          eval $CMD

      - name: Commit & push updated individuals
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add fca-dashboard/data/fca_individuals_by_firm.json
          git diff --cached --quiet || git commit -m "chore(fca): update firm individuals"
          git push origin HEAD:main
