name: Fetch FCA Individual Records (Threaded)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      threads:
        description: 'Number of parallel threads'
        required: true
        default: '5'
      limit:
        description: 'Max IRNs to process (blank = full run)'
        required: false
        default: ''
      only_missing:
        description: '☑️ Only fetch IRNs not in existing store'
        required: false
        default: false
        type: boolean
      retry_failed:
        description: '☑️ Only retry IRNs that errored last run'
        required: false
        default: false
        type: boolean
      fresh:
        description: '☑️ Full refresh: ignore existing records'
        required: false
        default: false
        type: boolean
      dry_run:
        description: '☑️ Dry run: list IRNs without API calls'
        required: false
        default: false
        type: boolean
      no_push:
        description: '☑️ Don’t commit/push the final JSON'
        required: false
        default: false
        type: boolean

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch individual records (threaded)
        env:
          FCA_API_EMAIL: ${{ secrets.FCA_API_EMAIL }}
          FCA_API_KEY:   ${{ secrets.FCA_API_KEY }}
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        run: |
          CMD="python3 fca-dashboard/scripts/fetch_persons.py --threads ${{ github.event.inputs.threads }}"
          if [ -n "${{ github.event.inputs.limit }}" ]; then
            CMD="$CMD --limit ${{ github.event.inputs.limit }}"
          fi
          if [ "${{ github.event.inputs.only_missing }}" = "true" ]; then
            CMD="$CMD --only-missing"
          fi
          if [ "${{ github.event.inputs.retry_failed }}" = "true" ]; then
            CMD="$CMD --retry-failed"
          fi
          if [ "${{ github.event.inputs.fresh }}" = "true" ]; then
            CMD="$CMD --fresh"
          fi
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            CMD="$CMD --dry-run"
          fi
          echo "▶️ Running: $CMD"
          $CMD

      - name: Commit & push updated persons
        if: ${{ github.event.inputs.no_push != 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add docs/fca-dashboard/data/fca_persons.json
          git diff --cached --quiet || git commit -m "chore(fca): update individual records"
          git pull --rebase origin main
          git push origin HEAD:main
