# .github/workflows/fetch-firm-individuals.yml
name: Fetch FCA Firm Individuals (Threaded)

# Allow pushing the final JSON back to main
permissions:
  contents: write

# Manual trigger with options for threads & testing limit
on:
  workflow_dispatch:
    inputs:
      threads:
        description: 'Number of parallel threads to use'
        required: true
        default: '5'
      limit:
        description: 'Max FRNs to process (blank = full run)'
        required: false
        default: ''

jobs:
  fetch:
    # You can enforce a timeout here if desired:
    # timeout-minutes: 360
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python  # ensure python3 & pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies  # bring in requests
        run: pip install requests

      - name: Fetch all firm individuals (threaded)
        # Expose API credentials and pass inputs through
        env:
          FCA_API_EMAIL: ${{ secrets.FCA_API_EMAIL }}
          FCA_API_KEY:   ${{ secrets.FCA_API_KEY }}
        run: |
          CMD="python3 fca-dashboard/scripts/fetch_firm_individuals.py --threads ${{ github.event.inputs.threads }}"
          if [ -n "${{ github.event.inputs.limit }}" ]; then
            CMD="$CMD --limit ${{ github.event.inputs.limit }}"
          fi
          echo "▶️ Running: $CMD"
          $CMD

      - name: Commit & push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"

          # Stage the updated JSON
          git add docs/fca-dashboard/data/fca_individuals_by_firm.json

          # Commit if changed
          git diff --cached --quiet || git commit -m "chore(fca): update firm individuals"

          # Integrate any remote changes and push
          git pull --rebase origin main
          git push origin HEAD:main
