# .github/workflows/update-data.yml
name: Update Fund Tracker Data

on:
  schedule:
    - cron: '0 * * * *'       # every hour
  workflow_dispatch:         # manual trigger

permissions:
  contents: write            # to push changes back to the repo

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      CH_API_KEY: ${{ secrets.CH_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip & install deps
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --prefer-binary --only-binary=:all: -r requirements.txt

      - name: Run company ingest
        run: |
          python fund_tracker.py \
            --start_date "${{ github.event.inputs.start_date || 'today' }}" \
            --end_date   "${{ github.event.inputs.end_date   || 'today' }}"

      - name: Run directors fetch
        run: python fetch_directors.py

      - name: Commit & push updated data in docs
        run: |
          git config user.email "bot@example.com"
          git config user.name  "GH Actions Bot"
          # Stage all CSV/XLSX/JSON under docs/assets/data
          git add docs/assets/data/master_companies.* \
                  docs/assets/data/relevant_companies.* \
                  docs/assets/data/directors.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📊 Update data: $(date -u +'%Y-%m-%dT%H:%MZ')"
            git push origin main
          fi
