name: Fund Tracker Automation

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD or "today")'
        default: 'today'
      end_date:
        description: 'End date (YYYY-MM-DD or "today")'
        default: 'today'
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write
  actions: read

concurrency:
  group: fund-tracker
  cancel-in-progress: true

jobs:
  run-fund-tracker:
    runs-on: ubuntu-latest
    env:
      CH_API_KEY: ${{ secrets.CH_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip & install deps
        run: |
          pip install --upgrade pip setuptools wheel
          pip install numpy
          pip install --prefer-binary --only-binary=:all: -r requirements.txt

      - name: Run fund_tracker.py
        run: python fund_tracker.py \
               --start_date "${{ github.event.inputs.start_date }}" \
               --end_date   "${{ github.event.inputs.end_date }}"

      # (…rest of your steps…)
