name: Fund Tracker

permissions:
  contents: write
  actions: read

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date for ingest (YYYY-MM-DD, today, or yesterday)'
        required: false
        default: 'today'
      end_date:
        description: 'End date for ingest (YYYY-MM-DD, today, or yesterday)'
        required: false
        default: 'today'

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      CH_API_KEY:   ${{ secrets.CH_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository (main)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Clone data branch and bootstrap existing data
        run: |
          git clone --branch data \
            https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} \
            data-branch
          mkdir -p docs/assets/data
          cp data-branch/docs/assets/data/master_companies.csv     docs/assets/data/  || true
          cp data-branch/docs/assets/data/master_companies.xlsx    docs/assets/data/  || true
          cp data-branch/docs/assets/data/relevant_companies.csv   docs/assets/data/  || true
          cp data-branch/docs/assets/data/relevant_companies.xlsx  docs/assets/data/  || true

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt

      - name: Run fund_tracker
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            SD="${{ github.event.inputs.start_date }}"
            ED="${{ github.event.inputs.end_date }}"
            [ -z "$SD" ] && SD="today"
            [ -z "$ED" ] && ED="today"
            python fund_tracker.py --start_date "$SD" --end_date "$ED"
          else
            python fund_tracker.py
          fi

      - name: Fetch directors for relevant companies
        run: python fetch_directors.py

      - name: Clone data branch for output
        run: |
          git clone --branch data \
            https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} \
            data-branch

      - name: Copy new data files into data-branch
        run: |
          mkdir -p data-branch/docs/assets/data
          cp docs/assets/data/master_companies.csv     data-branch/docs/assets/data/
          cp docs/assets/data/master_companies.xlsx    data-branch/docs/assets/data/
          cp docs/assets/data/relevant_companies.csv   data-branch/docs/assets/data/
          cp docs/assets/data/relevant_companies.xlsx  data-branch/docs/assets/data/
          cp docs/assets/data/directors.json           data-branch/docs/assets/data/
          cp docs/assets/data/no_directors.json        data-branch/docs/assets/data/

      - name: Commit & push updated data files to data branch
        run: |
          cd data-branch
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/assets/data/
          git diff --cached --quiet || (git commit -m "chore(data): update data files [skip ci]" && git push origin data)
