name: Fund Tracker Automation

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date to fetch (YYYY-MM-DD)'
        required: false
        default: 'today'  # Defaults to today if not provided
      end_date:
        description: 'End date to fetch (YYYY-MM-DD)'
        required: false
        default: 'today'  # Defaults to today if not provided

permissions:
  contents: write  # Grants write access to repository contents (e.g., files)
  actions: read    # Can adjust this to read if actions permissions are not needed

jobs:
  run-fund-tracker:
    runs-on: ubuntu-latest

    env:
      CH_API_KEY: ${{ secrets.CH_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run fund tracker script
        run: |
          python fund_tracker.py --start_date "${{ github.event.inputs.start_date }}" --end_date "${{ github.event.inputs.end_date }}"

      - name: Check for changes
        id: changes
        run: |
          git add master_companies.xlsx update_log.csv || true
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "GH Actions Bot"
          git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push

      - name: Upload update log (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: update-log
          path: update_log.csv
