name: Fund Tracker

permissions:
  contents: write
  actions: read

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date for ingest (YYYY-MM-DD, today, or yesterday)'
        required: false
        default: 'today'
      end_date:
        description: 'End date for ingest (YYYY-MM-DD, today, or yesterday)'
        required: false
        default: 'today'

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      CH_API_KEY:   ${{ secrets.CH_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # 1) Checkout code (main branch)
      - name: Check out repository (main)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2) Clone data-branch and bootstrap existing CSVs & JSONs
      - name: Bootstrap existing data from data branch
        run: |
          git clone --branch data \
            https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} \
            data-branch
          mkdir -p docs/assets/data
          cp data-branch/docs/assets/data/master_companies.csv   docs/assets/data/  || true
          # no more copying relevant_companies.csv/xlsx here
          cp data-branch/docs/assets/data/directors.json         docs/assets/data/  || true
          cp data-branch/docs/assets/data/no_directors.json      docs/assets/data/  || true

      # 3) Setup Python & install deps
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt

      # 4) Run the main ingest
      - name: Run fund_tracker
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            SD="${{ github.event.inputs.start_date }}"; ED="${{ github.event.inputs.end_date }}"
            [ -z "$SD" ] && SD="today"; [ -z "$ED" ] && ED="today"
            python fund_tracker.py --start_date "$SD" --end_date "$ED"
          else
            python fund_tracker.py
          fi

      # 5) Fetch directors for any newly relevant companies
      - name: Fetch directors for relevant companies
        run: python fetch_directors.py

      # 6) Copy & commit **only** master CSV back into data-branch
      - name: Copy master CSV into data-branch
        run: |
          mkdir -p data-branch/docs/assets/data
          cp docs/assets/data/master_companies.csv data-branch/docs/assets/data/
      - name: Commit & push master CSV to data branch
        run: |
          cd data-branch
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/assets/data/master_companies.csv
          git diff --cached --quiet || \
            (git commit -m "chore(data): update master CSV [skip ci]" && \
             git push origin data)

      # 7) Check out main and mirror **relevant_companies.csv** into it
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: main
          path: pages-branch

      - name: Copy relevant CSV to Pages branch
        run: |
          mkdir -p pages-branch/docs/assets/data
          cp docs/assets/data/relevant_companies.csv pages-branch/docs/assets/data/

      - name: Commit & push relevant CSV to main
        run: |
          cd pages-branch
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/assets/data/relevant_companies.csv
          git diff --cached --quiet || \
            (git commit -m "chore(pages): publish relevant_companies.csv [skip ci]" && \
             git push origin main)
