name: Fund Tracker Automation

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD or "today")'
        default: 'today'
      end_date:
        description: 'End date (YYYY-MM-DD or "today")'
        default: 'today'

permissions:
  contents: write
  actions: read

concurrency:
  group: fund-tracker
  cancel-in-progress: true

jobs:
  run-fund-tracker:
    runs-on: ubuntu-latest
    env:
      CH_API_KEY: ${{ secrets.CH_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Upgrade pip, setuptools, wheel
        run: pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config user.email "bot@example.com"
          git config user.name  "GH Actions Bot"

      # Stage 1: companies
      - name: Run fund_tracker.py
        run: python fund_tracker.py \
               --start_date "${{ github.event.inputs.start_date }}" \
               --end_date   "${{ github.event.inputs.end_date }}"

      - name: Commit data
        run: |
          git add assets/data/*.csv assets/data/*.xlsx
          if ! git diff --cached --quiet; then
            git commit -m "Stage 1: update companies data"
            git push origin main
          fi

      # Stage 2: directors
      - name: Run director fetch
        run: python fetch_directors.py

      - name: Commit directors.json
        run: |
          git add assets/data/directors.json
          if ! git diff --cached --quiet; then
            git commit -m "Stage 2: update directors"
            git push origin main
          fi

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: fund-tracker-logs
          path: assets/logs/fund_tracker.log
