name: Deploy Pages

on:
  push:
    branches:
      - main   # or your default branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build your site (adjust to your actual build commands)
      - name: Build site
        run: |
          echo "Building site…"
          mkdir -p public
          echo "<h1>Hello, Pages!</h1>" > public/index.html

      # 1) Configure Pages (v2)
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v2

      # 2) Upload the build output (v1)
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      # 3) Deploy to GitHub Pages (v2)
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
