name: Deploy Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # If you have any build steps for docs (e.g. MkDocs), run them here.
          # Otherwise skip this or leave as a no-op.

      - name: Copy docs to public
        run: |
          rm -rf public
          mkdir public
          # Copy over your entire docs folder: HTML, JS, CSS, assets, data, etc.
          cp -R docs/* public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
