name: "Retry No-Directors"

# Run daily at midnight UTC (00:00 UTC). Adjust if you want a different time.
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}  # allows manual trigger if needed

jobs:
  retry-no-directors:
    runs-on: ubuntu-latest
    env:
      CH_API_KEY:   ${{ secrets.CH_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt

      - name: Run retry_no_directors.py
        run: |
          python retry_no_directors.py

      # 5) Push updated JSONs back to the data branch
      - name: Clone data branch
        run: |
          git clone --branch data \
            https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} \
            data-branch

      - name: Copy updated JSONs into data-branch
        run: |
          mkdir -p data-branch/docs/assets/data
          cp docs/assets/data/directors.json      data-branch/docs/assets/data/
          cp docs/assets/data/no_directors.json   data-branch/docs/assets/data/

      - name: Commit & push to data branch
        run: |
          cd data-branch
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/assets/data/directors.json docs/assets/data/no_directors.json

          if git diff --cached --quiet; then
            echo "No changes to JSONs — skipping push"
            exit 0
          fi

          git commit -m "chore(data): update directors & no_directors JSONs [skip ci]"
          git push origin data
