# .github/workflows/update-frn-list.yml
name: Update FCA FRN List

permissions:
  contents: write

on:
  schedule:
    - cron: '0 3 * * 6'      # weekly on Saturday at 03:00 UTC
  workflow_dispatch:        # manual trigger still available

jobs:
  build-frn-list:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pandas beautifulsoup4

      - name: Refresh FRN list from FCA Resources
        run: python fca-dashboard/scripts/update_frn_list.py

      - name: Commit & push new FRN list
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add fca-dashboard/data/all_frns_with_names.json
          git diff --cached --quiet || git commit -m "chore(frns): weekly update FRN list"
          git push origin HEAD:main
