name: Verify CH API Key

on:
  workflow_dispatch:

jobs:
  verify-key:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # This will install `requests`
          pip install requests

      - name: Run API key test
        env:
          CH_API_KEY: ${{ secrets.CH_API_KEY }}
        run: python test_api_key.py
